# Generated by Django 4.0 on 2021-12-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(blank=True, max_length=100, null=True)),
                ('itemimage', models.ImageField(upload_to='media/')),
                ('itemdescription', models.CharField(blank=True, max_length=2000, null=True)),
                ('iteamfoundlocation', models.CharField(blank=True, max_length=200, null=True)),
                ('founderemail', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(blank=True, max_length=100, null=True)),
                ('itemimage', models.ImageField(upload_to='media/')),
                ('itemdescription', models.CharField(blank=True, max_length=2000, null=True)),
                ('iteamlostlocation', models.CharField(blank=True, max_length=200, null=True)),
                ('owneremail', models.EmailField(max_length=200)),
            ],
        ),
    ]
