# Generated by Django 4.0 on 2021-12-09 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0002_founditem_timecreated_lostitem_timecreated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='founditem',
            options={'ordering': ('-timecreated',)},
        ),
        migrations.AlterModelOptions(
            name='lostitem',
            options={'ordering': ('-timecreated',)},
        ),
        migrations.AddField(
            model_name='founditem',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
